// Generated by view binder compiler. Do not edit!
package com.example.weatherapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.SearchView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.helper.widget.Flow;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.airbnb.lottie.LottieAnimationView;
import com.example.weatherapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMainBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final TextView cityname;

  @NonNull
  public final TextView condition;

  @NonNull
  public final TextView data;

  @NonNull
  public final TextView day;

  @NonNull
  public final Flow flow3;

  @NonNull
  public final FrameLayout frameLayout;

  @NonNull
  public final TextView humidity;

  @NonNull
  public final LinearLayout linearLayout;

  @NonNull
  public final LinearLayout linearLayout2;

  @NonNull
  public final LinearLayout linearLayout3;

  @NonNull
  public final LinearLayout linearLayout4;

  @NonNull
  public final LinearLayout linearLayout5;

  @NonNull
  public final LinearLayout linearLayout6;

  @NonNull
  public final LottieAnimationView lottieAnimationView2;

  @NonNull
  public final TextView max;

  @NonNull
  public final TextView min;

  @NonNull
  public final TextView sea;

  @NonNull
  public final SearchView searchView;

  @NonNull
  public final TextView sunrise;

  @NonNull
  public final TextView sunset;

  @NonNull
  public final TextView temp;

  @NonNull
  public final TextView textView17;

  @NonNull
  public final TextView textView3;

  @NonNull
  public final TextView weather;

  @NonNull
  public final TextView wind;

  private ActivityMainBinding(@NonNull ConstraintLayout rootView, @NonNull TextView cityname,
      @NonNull TextView condition, @NonNull TextView data, @NonNull TextView day,
      @NonNull Flow flow3, @NonNull FrameLayout frameLayout, @NonNull TextView humidity,
      @NonNull LinearLayout linearLayout, @NonNull LinearLayout linearLayout2,
      @NonNull LinearLayout linearLayout3, @NonNull LinearLayout linearLayout4,
      @NonNull LinearLayout linearLayout5, @NonNull LinearLayout linearLayout6,
      @NonNull LottieAnimationView lottieAnimationView2, @NonNull TextView max,
      @NonNull TextView min, @NonNull TextView sea, @NonNull SearchView searchView,
      @NonNull TextView sunrise, @NonNull TextView sunset, @NonNull TextView temp,
      @NonNull TextView textView17, @NonNull TextView textView3, @NonNull TextView weather,
      @NonNull TextView wind) {
    this.rootView = rootView;
    this.cityname = cityname;
    this.condition = condition;
    this.data = data;
    this.day = day;
    this.flow3 = flow3;
    this.frameLayout = frameLayout;
    this.humidity = humidity;
    this.linearLayout = linearLayout;
    this.linearLayout2 = linearLayout2;
    this.linearLayout3 = linearLayout3;
    this.linearLayout4 = linearLayout4;
    this.linearLayout5 = linearLayout5;
    this.linearLayout6 = linearLayout6;
    this.lottieAnimationView2 = lottieAnimationView2;
    this.max = max;
    this.min = min;
    this.sea = sea;
    this.searchView = searchView;
    this.sunrise = sunrise;
    this.sunset = sunset;
    this.temp = temp;
    this.textView17 = textView17;
    this.textView3 = textView3;
    this.weather = weather;
    this.wind = wind;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.cityname;
      TextView cityname = ViewBindings.findChildViewById(rootView, id);
      if (cityname == null) {
        break missingId;
      }

      id = R.id.condition;
      TextView condition = ViewBindings.findChildViewById(rootView, id);
      if (condition == null) {
        break missingId;
      }

      id = R.id.data;
      TextView data = ViewBindings.findChildViewById(rootView, id);
      if (data == null) {
        break missingId;
      }

      id = R.id.day;
      TextView day = ViewBindings.findChildViewById(rootView, id);
      if (day == null) {
        break missingId;
      }

      id = R.id.flow3;
      Flow flow3 = ViewBindings.findChildViewById(rootView, id);
      if (flow3 == null) {
        break missingId;
      }

      id = R.id.frameLayout;
      FrameLayout frameLayout = ViewBindings.findChildViewById(rootView, id);
      if (frameLayout == null) {
        break missingId;
      }

      id = R.id.humidity;
      TextView humidity = ViewBindings.findChildViewById(rootView, id);
      if (humidity == null) {
        break missingId;
      }

      id = R.id.linearLayout;
      LinearLayout linearLayout = ViewBindings.findChildViewById(rootView, id);
      if (linearLayout == null) {
        break missingId;
      }

      id = R.id.linearLayout2;
      LinearLayout linearLayout2 = ViewBindings.findChildViewById(rootView, id);
      if (linearLayout2 == null) {
        break missingId;
      }

      id = R.id.linearLayout3;
      LinearLayout linearLayout3 = ViewBindings.findChildViewById(rootView, id);
      if (linearLayout3 == null) {
        break missingId;
      }

      id = R.id.linearLayout4;
      LinearLayout linearLayout4 = ViewBindings.findChildViewById(rootView, id);
      if (linearLayout4 == null) {
        break missingId;
      }

      id = R.id.linearLayout5;
      LinearLayout linearLayout5 = ViewBindings.findChildViewById(rootView, id);
      if (linearLayout5 == null) {
        break missingId;
      }

      id = R.id.linearLayout6;
      LinearLayout linearLayout6 = ViewBindings.findChildViewById(rootView, id);
      if (linearLayout6 == null) {
        break missingId;
      }

      id = R.id.lottieAnimationView2;
      LottieAnimationView lottieAnimationView2 = ViewBindings.findChildViewById(rootView, id);
      if (lottieAnimationView2 == null) {
        break missingId;
      }

      id = R.id.max;
      TextView max = ViewBindings.findChildViewById(rootView, id);
      if (max == null) {
        break missingId;
      }

      id = R.id.min;
      TextView min = ViewBindings.findChildViewById(rootView, id);
      if (min == null) {
        break missingId;
      }

      id = R.id.sea;
      TextView sea = ViewBindings.findChildViewById(rootView, id);
      if (sea == null) {
        break missingId;
      }

      id = R.id.searchView;
      SearchView searchView = ViewBindings.findChildViewById(rootView, id);
      if (searchView == null) {
        break missingId;
      }

      id = R.id.sunrise;
      TextView sunrise = ViewBindings.findChildViewById(rootView, id);
      if (sunrise == null) {
        break missingId;
      }

      id = R.id.sunset;
      TextView sunset = ViewBindings.findChildViewById(rootView, id);
      if (sunset == null) {
        break missingId;
      }

      id = R.id.temp;
      TextView temp = ViewBindings.findChildViewById(rootView, id);
      if (temp == null) {
        break missingId;
      }

      id = R.id.textView17;
      TextView textView17 = ViewBindings.findChildViewById(rootView, id);
      if (textView17 == null) {
        break missingId;
      }

      id = R.id.textView3;
      TextView textView3 = ViewBindings.findChildViewById(rootView, id);
      if (textView3 == null) {
        break missingId;
      }

      id = R.id.weather;
      TextView weather = ViewBindings.findChildViewById(rootView, id);
      if (weather == null) {
        break missingId;
      }

      id = R.id.wind;
      TextView wind = ViewBindings.findChildViewById(rootView, id);
      if (wind == null) {
        break missingId;
      }

      return new ActivityMainBinding((ConstraintLayout) rootView, cityname, condition, data, day,
          flow3, frameLayout, humidity, linearLayout, linearLayout2, linearLayout3, linearLayout4,
          linearLayout5, linearLayout6, lottieAnimationView2, max, min, sea, searchView, sunrise,
          sunset, temp, textView17, textView3, weather, wind);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
